%  Collect data 
XDP = [6.5 8.5 6.5 5.5 3];
P4 = [8 1.5 1.5 9.5 7];
P = [XDP; P4];

% Plot
hFig = figure('Renderer', 'painters', 'Position', [10 10 850 500]);


% Spider plot
spider_plot(P,...
            'AxesInterval', 9,...
            'AxesPrecision', 0,...
            'AxesDisplay', 'none',...
            'AxesLabelsEdge', 'none',...
            'AxesLimits', [1, 1, 1, 1, 1; 10, 10, 10, 10, 10],...
            'AxesLabels', {'Documentation quality', 'Independence from other software', 'Migration and updates', 'Potential integration in SDN environments', 'Hardware integration'},...
            'FillOption', 'on',...
            'FillTransparency', 0.1,...
            'LineWidth', 2,...
            'Marker', 'o');
      
legend({'XDP', 'P4'}, 'Orientation', 'horizontal','Location', 'northoutside');

% Export figure
set(hFig,'Units','Inches');
pos = get(hFig,'Position');
set(hFig,'PaperPositionMode','Auto','PaperUnits','Inches','PaperSize',[pos(3), pos(4)])
print(hFig,'07_Qualitative','-dpdf','-r0')

